mysite/authapp/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView


app_name = 'authapp'
urlpatterns = [
    path('', TemplateView.as_view(template_name='authapp/main.html')),
    path('open', views.OpenView.as_view(), name='open'),
    path('manual', views.ManualProtect.as_view(), name='manual'),
    path('protect', views.ProtectView.as_view(), name='protect'),
    path('python', views.DumpPython.as_view(), name='python'),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("authapp/", include("authapp.urls")),
    path("polls/", include("polls.urls")),
] + debug_toolbar_urls()

mysite/polls/urls.py
from django.urls import path

from . import views

# namespace for the polls app, this allows us to refer to
# urls unambiguously, i.e. 'polls:index' in templates
app_name = "polls"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("api/<int:id>", views.api, name="api"),
    path("class", views.ClassBasedView.as_view(), name="class"),
    path("bounce", views.bounce, name="bounce"),
    path("templated/<str:param>", views.TemplatedView.as_view(),
         name="templated"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
]

mysite/authapp/models.py
from django.db import models

# Create your models here.

mysite/polls/models.py
import datetime
from django.db import models
from django.utils import timezone
from django.contrib import admin

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")

    def __str__(self):
        return self.question_text

    @admin.display(
        boolean=True,
        ordering="pub_date",
        description="Published recently?",
    )
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

mysite/authapp/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.http import urlencode
from django.http import HttpResponse


class OpenView(View):
    def get(self, request):
        return render(request, 'authapp/main.html')


class ManualProtect(View):
    def get(self, request):
        if not request.user.is_authenticated:
            loginurl = reverse('login')+'?'+urlencode({'next': request.path})
            return redirect(loginurl)
        return render(request, 'authapp/main.html')


class ProtectView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, 'authapp/main.html')


class DumpPython(View):
    def get(self, req):
        resp = "<pre>\nUser Data in Python:\n\n"
        resp += "Login url: " + reverse('login') + "\n"
        resp += "Logout url: " + reverse('logout') + "\n\n"
        if req.user.is_authenticated:
            resp += "User: " + req.user.username + "\n"
            resp += "Email: " + req.user.email + "\n"
        else:
            resp += "User is not logged in\n"

        resp += "\n"
        resp += "</pre>\n"
        resp += """<a href="/authapp">Go back</a>"""
        return HttpResponse(resp)


# https://docs.djangoproject.com/en/4.2/topics/auth/default/#authentication-in-web-requests

mysite/polls/views.py
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.utils.html import escape
from django.views import View, generic
from polls.models import Question, Choice
from django.db.models import F
from django.shortcuts import get_object_or_404, render
from django.urls import reverse


class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now())\
            .order_by("-pub_date")[:5]


def api(request, id):
    return HttpResponse(f"<html><body><h1>API Endpoint</h1>"
                        f"<p>You requested the API with id={escape(id)}.</p>"
                        "</body></html>")


class ClassBasedView(View):
    def get(self, request):
        return HttpResponse("<html><body><h1>Class Based View</h1>"
                            "<p>This is from a class-based view.</p>"
                            f"<p>You requested with url={request.path}.</p>"
                            "</body></html>")


def bounce(request):
    return HttpResponseRedirect("/polls/?param=redirected")


class TemplatedView(View):
    def get(self, request, param):
        info = {'param': param}
        return render(request, 'templated.html', info)


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes = F("votes") + 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results",
                                    args=(question.id,)))

mysite/authapp/templates/authapp/main.html
<h1>Current request.path {{ request.path }}</h1>
{% if user.is_authenticated %}
<p>Authenticated as
<pre>
Name: {{ user.get_full_name }}
Email: {{ user.email }}
Id: {{ user.id }}
</pre>
</p>
<p>You can <a href="{% url 'logout' %}?next={% url 'authapp:open' %}">Logout</a></p>
{% else %}
<p>You are not logged in</p>
<p>You can <a href="{% url 'login' %}?next={{ request.path }}">Login</a> if you like.</p>
{% endif %}
<ul>
    <li>
        Go to <a href="{% url 'authapp:open' %}">{% url 'authapp:open' %}</a>
            (no login required)
    </li>
    <li>
        Go to <a href="{% url 'authapp:manual' %}">{% url 'authapp:manual' %}</a>
            (protected by user.is_authenticated)
    </li>
    <li>
        Go to <a href="{% url 'authapp:protect' %}">{% url 'authapp:protect' %}</a>
            (protected by LoginRequiredMixin)
    </li>
    <li>
        Go to <a href="{% url 'authapp:python' %}">{% url 'authapp:python' %}</a>
            dump request.user data in python
    </li>
</ul>

mysite/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

mysite/polls/templates/polls/index.html
{% load static %}

<link rel="stylesheet" href="{% static 'polls/style.css' %}">
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

mysite/polls/templates/templated.html
<html>
    <head>
        <title>Templated View</title>
    </head>
    <body>
        <h1>Templated View</h1>
        <p>This view simulates template rendering.</p>
        <p>You requested with param={{ param }}.</p>
    </body>
</html>